nhn-on7/marketgg-shop

- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
> Fix: 상품 등록 테스트코드 수정

- src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
- src/test/java/com/nhnacademy/marketgg/server/controller/ProductControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/repository/ProductRepositoryTest.java
테스트 코드 작성이 정상적으로 됐는지 확인부탁드립니다.
> Test/product controller test 

- productRequest.http
- src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
- src/main/java/com/nhnacademy/marketgg/server/dto/request/ProductCreateRequest.java
- src/main/java/com/nhnacademy/marketgg/server/dto/request/ProductUpdateRequest.java
- src/main/java/com/nhnacademy/marketgg/server/dto/response/ProductResponse.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Category.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Product.java
- src/main/java/com/nhnacademy/marketgg/server/exception/AssetNotFoundException.java
- src/main/java/com/nhnacademy/marketgg/server/repository/AssetRepository.java
- src/main/java/com/nhnacademy/marketgg/server/repository/CategoryRepository.java
- src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
- src/test/java/com/nhnacademy/marketgg/server/controller/ProductControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/repository/ProductRepositoryTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
엔티티 수정과 controller, test 코드 수정했습니다.
> 상품 엔티티 속성 수정 및 controller, test 코드 수정

- src/main/java/com/nhnacademy/marketgg/server/controller/CategoryController.java
- src/main/java/com/nhnacademy/marketgg/server/dto/CategoryCreateRequest.java
- src/main/java/com/nhnacademy/marketgg/server/dto/CategoryRegisterRequest.java
- src/main/java/com/nhnacademy/marketgg/server/dto/CategoryRequest.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Categorization.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Category.java
- src/main/java/com/nhnacademy/marketgg/server/exception/CategorizationNotFoundException.java
- src/main/java/com/nhnacademy/marketgg/server/service/CategoryService.java
- src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryService.java
- src/test/java/com/nhnacademy/marketgg/server/controller/CategoryControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryServiceTest.java
Category Create 수정 완료 했습니다. 확인 부탁드립니다.
> 카테고리 생성 구현/테스트 코드 PR

- src/main/resources/application.yml
포트번호 설정이 아직 안 되어 있어서, API 명세에 적혀진 포트번호로 바꾸었습니다.
> Chore: .yml 포트번호 7080으로 변경

- src/main/java/com/nhnacademy/marketgg/server/controller/MemberController.java
- src/main/java/com/nhnacademy/marketgg/server/dto/request/MemberCreateRequest.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Member.java
- src/main/java/com/nhnacademy/marketgg/server/exception/categorization/CategorizationNotFoundException.java
- src/main/java/com/nhnacademy/marketgg/server/exception/category/CategoryNotFoundException.java
- src/main/java/com/nhnacademy/marketgg/server/exception/member/MemberNotFoundException.java
- src/main/java/com/nhnacademy/marketgg/server/service/MemberService.java
- src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberService.java
- src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
- src/test/java/com/nhnacademy/marketgg/server/controller/MemberControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategorizationServiceTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryServiceTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultLabelServiceTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberServiceTest.java
- 테스트 코드 정상 작동
- Exception 메세지 처리 부분 수정
- @SpringBootTest 에노테이션 -> ExtendWith(MockitoExtension.class) 수정 완료
> GG 패스 테스트 수정 완료 PR

- readme/products.md
- src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
- src/main/java/com/nhnacademy/marketgg/server/httprequest/productRequest.http
- src/main/java/com/nhnacademy/marketgg/server/repository/ProductRepository.java
- src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
- src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
- #79 
다음과 같은 메서드 사용
```
findByCategory_CategoryCodeAndCategory_Categorization_CategorizationCode(String categorizationCode,String categoryCode);
```
```
GET http://localhost:7080/admin/v1/products/search/100/001
Content-Type: application/json
```
```
[
{
"description": "<p>ㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁ</p>",
"origin": "원산지",
"name": "자몽주스",
"content": "컨텐트",
"asset": {
"assetNo": 21,
"createAt": "2022-07-14 13:19:23",
"updateAt": "2022-07-14 13:19:23",
"deletedAt": null
},
"price": 10000,
"unit": "단위",
"createdAt": "2022-07-10T19:47:33",
"productNo": 1,
"category": {
"categoryCode": "001",
"categorization": {
"categorizationCode": "100",
"name": "PROD",
"alias": "상품"
},
"name": "채소",
"sequence": 1
},
...
```
> Feat: 카테고리 코드로 상품 검색기능 구현 #79

- src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
> Fix: 맵핑 변경

- src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Asset.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Image.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Product.java
- src/main/java/com/nhnacademy/marketgg/server/repository/ProductRepository.java
- src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
- #82 
- 상품 관리에 해당하는 소스코드에  Java Docs 추가
> Docs: 상품 Java Docs 추가 #82

- src/main/java/com/nhnacademy/marketgg/server/controller/CategorizationController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/CategoryController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/LabelController.java
---
- 아래에 해당하는 Controller 에서 변경된 URI 로 매핑을 수정하였습니다.
- Category, Categorization, Label
- 한 Controller 에서 중복되는 URI 값들을 변수로 선언하였습니다.
> 카테고리 관련 URI 매핑 수정

- src/main/java/com/nhnacademy/marketgg/server/controller/CategorizationController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/CategoryController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/GlobalControllerAdvice.java
- src/main/java/com/nhnacademy/marketgg/server/controller/LabelController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/MemberController.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Categorization.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Category.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Label.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Member.java
- src/main/java/com/nhnacademy/marketgg/server/exception/categorization/CategorizationNotFoundException.java
- src/main/java/com/nhnacademy/marketgg/server/exception/category/CategoryNotFoundException.java
- src/main/java/com/nhnacademy/marketgg/server/exception/label/LabelNotFoundException.java
- src/main/java/com/nhnacademy/marketgg/server/exception/member/MemberNotFoundException.java
- src/main/java/com/nhnacademy/marketgg/server/exception/membergrade/MemberGradeNotFoundException.java
- src/main/java/com/nhnacademy/marketgg/server/service/CategorizationService.java
- src/main/java/com/nhnacademy/marketgg/server/service/CategoryService.java
- src/main/java/com/nhnacademy/marketgg/server/service/LabelService.java
- src/main/java/com/nhnacademy/marketgg/server/service/MemberService.java
- src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategorizationService.java
- src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryService.java
- src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultLabelService.java
- src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberService.java
- src/test/java/com/nhnacademy/marketgg/server/controller/MemberControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberServiceTest.java
- Member Controller/Service/Entity JavaDocs 작성
- Category Controller/Service/Entity JavaDocs 작성
- Categorization Controller/Service/Entity JavaDocs 작성
- Label Controller/Service/Entity JavaDocs 작성 및 Controller 코드 수정
- GGPass 구현 및 테스트 코드 작성 완료
> JavaDocs 작성 및 GG PASS 코드 수정

- pom.xml
- src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Asset.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Categorization.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Category.java
- src/main/java/com/nhnacademy/marketgg/server/httprequest/productRequest.http
- src/test/java/com/nhnacademy/marketgg/server/controller/ProductControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
> Refactor: PR 코멘트 받은 부분 수정

- src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
- src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
- src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
- Controller
- Service
- Repository
- 인자에 final 추가
- 클래스 내 메소드에 this. 추가
> Style: 코딩 컨벤션대로 수정

- src/main/java/com/nhnacademy/marketgg/server/httprequest/prodcutInquiryPostRequest.http
- src/test/java/com/nhnacademy/marketgg/server/controller/AdminProductInquiryPostControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/controller/ProductInquiryPostControllerTest.java
-  Admin controller Test 분리
-  회원의 마이페이지 내에서 상품 문의 조회 URI 수정
> Fix: 상품 문의 관리 Test Code 수정

- src/main/java/com/nhnacademy/marketgg/server/controller/AdminProductInquiryPostController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/CategorizationController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/CategoryController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/DibController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/LabelController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/MemberController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/ProductAdminController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/ProductInquiryPostController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/ProductMemberController.java
- src/main/java/com/nhnacademy/marketgg/server/service/DibService.java
- close #107 
- 찜 구현 시 누락되었던 JavaDoc 을 작성하였습니다.
- DibController JavaDoc 작성
- DibService JavaDoc 작성
- optional
> Docs: 누락된 찜 JavaDoc 작성 #107

- pom.xml
- src/main/java/com/nhnacademy/marketgg/server/controller/CategoryController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/GlobalControllerAdvice.java
- src/main/java/com/nhnacademy/marketgg/server/dto/request/CategorizationCreateRequest.java
- src/main/java/com/nhnacademy/marketgg/server/dto/request/CategoryCreateRequest.java
- src/main/java/com/nhnacademy/marketgg/server/dto/request/CategoryUpdateRequest.java
- src/main/java/com/nhnacademy/marketgg/server/dto/response/CategorizationRetrieveResponse.java
- src/main/java/com/nhnacademy/marketgg/server/dto/response/CategoryRetrieveResponse.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Categorization.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Category.java
- src/test/java/com/nhnacademy/marketgg/server/controller/CategoryControllerTest.java
- close #110 
- 카테고리 관리 Validation 적용
- Entity, Dto, Controller 에서 Validation 조건 추가 및 검사
- Validation 예외 처리 분리
- 에러 메시지 작성
- 2022.07.21 15:41 현재 제품 코드 작성 완료하였는데 reviewer 분들 한번 확인 부탁 드립니다.
- 2022.07.21 16:42 에러 메시지 작성 캡쳐 게시합니다.
- 카테고리 등록 시 category_code 가 6자를 초과할 경우 에러
> 카테고리 Validation 적용

- src/main/java/com/nhnacademy/marketgg/server/controller/AdminProductInquiryPostController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/ProductAdminController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/ProductMemberController.java
- src/main/java/com/nhnacademy/marketgg/server/httprequest/productRequest.http
- src/main/java/com/nhnacademy/marketgg/server/repository/product/ProductRepositoryCustom.java
- src/main/java/com/nhnacademy/marketgg/server/repository/product/ProductRepositoryImpl.java
- src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
- src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
- src/test/java/com/nhnacademy/marketgg/server/controller/ProductAdminControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/controller/ProductMemberControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/repository/product/ProductRepositoryImplTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
- #116 
- 전체 상품 조회 페이지네이션 구현
- 카테고리로 상품 조회 페이지네이션 구현
closed
> 상품관리 페이지네이션

- src/main/java/com/nhnacademy/marketgg/server/controller/ProductInquiryPostController.java
- src/main/java/com/nhnacademy/marketgg/server/httprequest/prodcutInquiryPostRequest.http
- src/main/java/com/nhnacademy/marketgg/server/repository/productinquirypost/ProductInquiryPostRepositoryCustom.java
- src/main/java/com/nhnacademy/marketgg/server/repository/productinquirypost/ProductInquiryPostRepositoryImpl.java
- src/main/java/com/nhnacademy/marketgg/server/service/ProductInquiryPostService.java
- src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductInquiryPostService.java
- src/test/java/com/nhnacademy/marketgg/server/controller/ProductInquiryPostControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductInquiryPostServiceTest.java
Feat: 상품 문의 조회 Pagination 구현 #86
- 상품 번호로 상품 문의 전체 조회 Pagination
- 회원 번호로 상품 문의 전체 조회 Pagination
> Feature/ 상품 문의 조회 Pagination 구현 #86

- pom.xml
- src/main/java/com/nhnacademy/marketgg/server/aop/RoleCheckAspect.java
- src/main/java/com/nhnacademy/marketgg/server/aop/annotation/Role.java
- src/main/java/com/nhnacademy/marketgg/server/aop/annotation/RoleCheck.java
- src/main/java/com/nhnacademy/marketgg/server/controller/AuthControllerAdvice.java
- src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
- src/main/java/com/nhnacademy/marketgg/server/exception/auth/UnAuthenticException.java
- src/main/java/com/nhnacademy/marketgg/server/exception/auth/UnAuthorizationException.java
- src/main/resources/application.yml
- #102 
- 어노테이션과 AOP 를 이용한 사용자 권한 체크
- 컨트롤러 클래스의 메서드에 어노테이션으로 사용자 접근을 관리할 수 있다.
- `@RoleCheck`
- [참조](https://nhnacademy.dooray.com/wiki/3300049102934826191/3320483677884978458)
> Shop API 서버에서 사용자 접근 권한 체크 

- pom.xml
- src/main/java/com/nhnacademy/marketgg/server/ServerApplication.java
- src/main/java/com/nhnacademy/marketgg/server/config/ElasticSearchConfig.java
- src/main/java/com/nhnacademy/marketgg/server/controller/ProductMemberController.java
- src/main/java/com/nhnacademy/marketgg/server/dto/request/EsProductSearchRequest.java
- src/main/java/com/nhnacademy/marketgg/server/elasticrepository/EsProductRepository.java
- src/main/java/com/nhnacademy/marketgg/server/elasticrepository/EsRepositoryMarker.java
- src/main/java/com/nhnacademy/marketgg/server/entity/elastic/EsProduct.java
- src/main/java/com/nhnacademy/marketgg/server/repository/JpaRepositoryMarker.java
- src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
- src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
- src/main/resources/application.yml
- ES Server 연동 및 현재 사용하고 있는 MySql의 데이터베이스와 동기화를 위한 작업
- ElasticConfig 작성
- yml ES Server host, port 작성
- ElasticRepository 및 Elastic Document 생성
- 보시면서 궁금하신점은 여쭤봐주세요. 추가적으로 후에 기술공유때 더 자세히 말씀드리겠습니다.
> Shop ES(Elastic Search) Server 연동

- src/main/java/com/nhnacademy/marketgg/server/annotation/Auth.java
- src/main/java/com/nhnacademy/marketgg/server/annotation/RoleCheck.java
- src/main/java/com/nhnacademy/marketgg/server/aop/AuthInjectAspect.java
- src/main/java/com/nhnacademy/marketgg/server/aop/RoleCheckAspect.java
- src/main/java/com/nhnacademy/marketgg/server/controller/MemberController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/advice/GlobalControllerAdvice.java
- src/main/java/com/nhnacademy/marketgg/server/controller/advice/MemberControllerAdvice.java
- src/main/java/com/nhnacademy/marketgg/server/dto/response/MemberResponse.java
- src/main/java/com/nhnacademy/marketgg/server/dto/response/common/CommonResponse.java
- src/main/java/com/nhnacademy/marketgg/server/dto/response/common/ErrorEntity.java
- src/main/java/com/nhnacademy/marketgg/server/dto/response/common/ListResponse.java
- src/main/java/com/nhnacademy/marketgg/server/dto/response/common/SingleResponse.java
- src/main/java/com/nhnacademy/marketgg/server/exception/auth/UnAuthorizationException.java
- src/main/java/com/nhnacademy/marketgg/server/repository/member/MemberRepository.java
- src/main/java/com/nhnacademy/marketgg/server/service/MemberService.java
- src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberService.java
- src/main/resources/application.yml
- src/test/java/com/nhnacademy/marketgg/server/controller/MemberControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberServiceTest.java
- #127
- 회원 정보 API 개발
- 공통응답클래스 이용
- `GlobalControllerAdvice` 모든 예외를 처리하여 세부적인 설정이 안되는 문제가 있었음.
- `GlobalControllerAdvice` 에 `@Order` 사용하여 가장 낮은 우선순위 부여
> 가장 `@Order` 의 기본 값은 `Integer.MAX_VALUE` (숫자가 클 수록 우선순위가 낮음)
> 회원 정보 API 개발

- src/main/java/com/nhnacademy/marketgg/server/config/WebConfig.java
- 인코딩 설정
- WebConfig 에 문자열 인코딩 추가
> Feat: 문자열 인코딩 필터 설정

- src/main/java/com/nhnacademy/marketgg/server/aop/AspectUtils.java
- src/main/java/com/nhnacademy/marketgg/server/aop/RoleCheckAspect.java
- src/main/java/com/nhnacademy/marketgg/server/controller/advice/MemberControllerAdvice.java
- src/test/java/com/nhnacademy/marketgg/server/controller/CartControllerTest.java
> Hotfix: Auth AOP 수정

- src/main/java/com/nhnacademy/marketgg/server/aop/MemberInfoAspect.java
- src/main/java/com/nhnacademy/marketgg/server/dto/MemberInfo.java
- Close #187 
- MemberInfo 클래스 권한관리
- MemberInfo 클래스 권한 체크 추가
- MemberInfo 클래스 확인 부탁드립니다. ⭐️
> MemberInfo 클래스 권한 관리

- src/main/java/com/nhnacademy/marketgg/server/service/post/DefaultPostService.java
- src/main/java/com/nhnacademy/marketgg/server/service/product/DefaultProductService.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultPostServiceTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
closed #201 
1. 엘라스틱 서치 동기화로 인한 메소드 수정
> 엘라스틱 서치 동기화로 인한 메소드 수정

- src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminCategorizationController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminCategoryController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminCsPostController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminLabelController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminPointController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/customerservice/CommentController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/customerservice/CsPostController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/member/MemberController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/member/PointController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/product/ProductController.java
- src/main/java/com/nhnacademy/marketgg/server/dto/ShopResult.java
- src/main/java/com/nhnacademy/marketgg/server/elastic/dto/request/SearchRequest.java
- src/main/java/com/nhnacademy/marketgg/server/elastic/dto/request/SearchRequestBodyForBool.java
- src/main/java/com/nhnacademy/marketgg/server/elastic/repository/SearchAdapter.java
- src/main/java/com/nhnacademy/marketgg/server/elastic/repository/SearchRepository.java
- src/main/java/com/nhnacademy/marketgg/server/service/post/DefaultPostService.java
- src/main/java/com/nhnacademy/marketgg/server/service/post/PostService.java
- src/main/java/com/nhnacademy/marketgg/server/service/product/DefaultProductService.java
- src/main/java/com/nhnacademy/marketgg/server/service/product/ProductService.java
- src/test/java/com/nhnacademy/marketgg/server/controller/CsPostControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/controller/ProductControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/controller/admin/AdminCsPostControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/dummy/Dummy.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultPostServiceTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
- closed #228 
- 클라이언트의 미흡한 Validation 처리 수정에 따른 Shop 변경 요소 추가
- optional
> Validation 처리 수정 및 리뷰 반영

- src/main/java/com/nhnacademy/marketgg/server/controller/member/MemberController.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Order.java
- src/main/java/com/nhnacademy/marketgg/server/entity/ProductInquiryPost.java
- src/main/java/com/nhnacademy/marketgg/server/repository/member/MemberRepositoryImpl.java
- src/main/java/com/nhnacademy/marketgg/server/repository/productinquirypost/ProductInquiryPostRepository.java
- src/main/java/com/nhnacademy/marketgg/server/repository/productinquirypost/ProductInquiryPostRepositoryImpl.java
- src/main/java/com/nhnacademy/marketgg/server/service/product/DefaultProductInquiryPostService.java
- src/main/java/com/nhnacademy/marketgg/server/service/product/ProductInquiryPostService.java
- src/test/java/com/nhnacademy/marketgg/server/repository/productinquirypost/ProductInquiryPostRepositoryImplTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductInquiryPostServiceTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultUsedCouponServiceTest.java
- 상품 문의 Entity 수정
- 상품 문의 Entity 에서 복합키 ->  인조식별키 하나로 수정
> Refactor: 상품 문의 Entity 수정

- src/main/java/com/nhnacademy/marketgg/server/aop/AuthInfoAspect.java
- src/main/java/com/nhnacademy/marketgg/server/dto/response/cart/CartProductResponse.java
- src/main/java/com/nhnacademy/marketgg/server/repository/cart/CartProductRepositoryImpl.java
- src/main/java/com/nhnacademy/marketgg/server/repository/image/ImageRepositoryImpl.java
- src/test/java/com/nhnacademy/marketgg/server/repository/cart/CartProductRepositoryTest.java
- Close #263
- 장바구니 로직 수정
- 장바구니 로직 수정 (QueryDSL)
> Refactor: 장바구니 로직 수정 #263

- src/main/java/com/nhnacademy/marketgg/server/controller/order/OrderController.java
- src/main/java/com/nhnacademy/marketgg/server/repository/order/OrderRepositoryCustom.java
- src/main/java/com/nhnacademy/marketgg/server/repository/order/OrderRepositoryImpl.java
- src/main/java/com/nhnacademy/marketgg/server/service/order/DefaultOrderService.java
- src/main/java/com/nhnacademy/marketgg/server/service/order/OrderService.java
- src/test/java/com/nhnacademy/marketgg/server/controller/OrderControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultOrderServiceTest.java
- #266 
- 주문 UI 와 함께 병행되는 수정
- #266 이슈 삭제하면 안됩니다.
> 주문 UI 와 함께하는 수정

- src/main/java/com/nhnacademy/marketgg/server/controller/member/DeliveryAddressController.java
- src/main/java/com/nhnacademy/marketgg/server/dto/request/deliveryaddress/DeliveryAddressCreateRequest.java
- src/main/java/com/nhnacademy/marketgg/server/dto/response/deliveryaddress/DeliveryAddressResponse.java
- src/main/java/com/nhnacademy/marketgg/server/entity/DeliveryAddress.java
- src/main/java/com/nhnacademy/marketgg/server/exception/deliveryaddresses/MinimumDeliveryAddressCountException.java
- src/main/java/com/nhnacademy/marketgg/server/repository/deliveryaddress/DeliveryAddressRepositoryImpl.java
- src/main/java/com/nhnacademy/marketgg/server/service/deliveryaddress/DefaultDeliveryAddressService.java
- src/main/java/com/nhnacademy/marketgg/server/service/deliveryaddress/DeliveryAddressService.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultDeliveryAddressServiceTest.java
> Refactor: 배송지 관리 최종본

- src/main/java/com/nhnacademy/marketgg/server/controller/product/ProductController.java
- src/main/java/com/nhnacademy/marketgg/server/elastic/dto/request/SearchRequestBodyForBool.java
- src/main/java/com/nhnacademy/marketgg/server/elastic/repository/SearchAdapter.java
- src/main/java/com/nhnacademy/marketgg/server/repository/auth/AuthAdapter.java
- src/main/java/com/nhnacademy/marketgg/server/service/product/DefaultProductService.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
-closed #274 
1. 상품 검색 버그 수정
- optional
> 상품 검색 버그 수정

- src/main/java/com/nhnacademy/marketgg/server/controller/product/ReviewController.java
- src/main/java/com/nhnacademy/marketgg/server/dto/response/review/ReviewRatingResponse.java
- src/main/java/com/nhnacademy/marketgg/server/repository/review/ReviewRepositoryCustom.java
- src/main/java/com/nhnacademy/marketgg/server/repository/review/ReviewRepositoryImpl.java
- src/main/java/com/nhnacademy/marketgg/server/service/product/DefaultReviewService.java
- src/main/java/com/nhnacademy/marketgg/server/service/product/ReviewService.java
- src/test/java/com/nhnacademy/marketgg/server/controller/ReviewControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultReviewServiceTest.java
> 리뷰 별점 구현 및 UI 수정

- src/main/java/com/nhnacademy/marketgg/server/controller/order/OrderController.java
- src/main/java/com/nhnacademy/marketgg/server/dto/request/order/CartOrderRequest.java
- src/main/java/com/nhnacademy/marketgg/server/dto/request/order/ProductToOrder.java
- src/main/java/com/nhnacademy/marketgg/server/repository/cart/CartProductRepositoryImpl.java
- src/test/java/com/nhnacademy/marketgg/server/controller/OrderControllerTest.java
- Closes #284 
- 장바구니 - 주문 - 결제 연동을 위한 수정 작업
> 주문 프로세스 연동

- src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminCsPostController.java
- src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminMemberController.java
- src/main/java/com/nhnacademy/marketgg/server/dto/request/DefaultPageRequest.java
- src/main/java/com/nhnacademy/marketgg/server/dto/response/member/AdminAuthResponse.java
- src/main/java/com/nhnacademy/marketgg/server/dto/response/member/AdminMemberResponse.java
- src/main/java/com/nhnacademy/marketgg/server/repository/auth/AuthAdapter.java
- src/main/java/com/nhnacademy/marketgg/server/repository/auth/AuthRepository.java
- src/main/java/com/nhnacademy/marketgg/server/service/member/DefaultMemberService.java
- src/main/java/com/nhnacademy/marketgg/server/service/member/MemberService.java
- src/test/java/com/nhnacademy/marketgg/server/controller/admin/AdminMemberControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/dummy/DummyPageEntity.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberServiceTest.java
- Close #287 
- 관리자 회원 정보 조회 API
- 관리자 회원 정보 조회 API
- 테스트 코드
> 관리자 회원 정보 조회 API 개발

- src/main/java/com/nhnacademy/marketgg/server/config/WebConfig.java
- src/main/java/com/nhnacademy/marketgg/server/filter/SecurityFilter.java
- 필터를 통해 특정 IP 에서만 응답
- 요청 IP 로깅
- 추후 Gateway 외에서 요청 시 응답 안하도록 설정할 예정
> Feat: Gateway 에서의 호출만 응답하도록 설정

- src/main/java/com/nhnacademy/marketgg/server/dto/request/file/ImageCreateRequest.java
- src/main/java/com/nhnacademy/marketgg/server/dto/request/product/ProductCreateRequest.java
- src/main/java/com/nhnacademy/marketgg/server/dto/request/product/ProductUpdateRequest.java
- src/main/java/com/nhnacademy/marketgg/server/dto/response/file/ImageResponse.java
- src/main/java/com/nhnacademy/marketgg/server/entity/Image.java
- src/main/java/com/nhnacademy/marketgg/server/repository/image/ImageRepository.java
- src/main/java/com/nhnacademy/marketgg/server/repository/image/ImageRepositoryImpl.java
- src/main/java/com/nhnacademy/marketgg/server/service/file/DefaultFileService.java
- src/main/java/com/nhnacademy/marketgg/server/service/storage/LocalStorageService.java
- src/main/java/com/nhnacademy/marketgg/server/service/storage/NhnStorageService.java
- src/test/java/com/nhnacademy/marketgg/server/controller/FileControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/controller/admin/AdminProductControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultFileServiceTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultReviewServiceTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/NhnStorageServiceTest.java
- 상품, 후기, 이미지 엔티티 DB 컬럼 수정에 따른 Refactoring
- ObjectStorage 이미지 업로드 로직 변경
- 상품: 재고 데이터 타입 Long -> Small Int 변경에 따라 Validation 1~65535 추가 및 테스트코드 추가
- 후기: 별점 tiny int로 변경
- 이미지: ImageSequence 속성 삭제
- ObjectStorage 이미지 업로드시 File을 만들지 않고 바로 InputStream을 resttemplate으로 보낸다.
> 상품 DDL 수정에 따른 Refactoring

- src/main/java/com/nhnacademy/marketgg/server/constant/MemberBenefits.java
- src/main/java/com/nhnacademy/marketgg/server/constant/PointContent.java
- src/main/java/com/nhnacademy/marketgg/server/controller/payment/PaymentController.java
- src/main/java/com/nhnacademy/marketgg/server/dto/payment/request/PaymentConfirmRequest.java
- src/main/java/com/nhnacademy/marketgg/server/dto/request/point/PointHistoryRequest.java
- src/main/java/com/nhnacademy/marketgg/server/eventlistener/event/order/OrderCartUpdatedEvent.java
- src/main/java/com/nhnacademy/marketgg/server/eventlistener/event/order/OrderCouponUsedEvent.java
- src/main/java/com/nhnacademy/marketgg/server/eventlistener/event/order/OrderPointSavedEvent.java
- src/main/java/com/nhnacademy/marketgg/server/eventlistener/event/order/OrderProductUpdatedEvent.java
- src/main/java/com/nhnacademy/marketgg/server/eventlistener/handler/OrderCartUpdatedEventHandler.java
- src/main/java/com/nhnacademy/marketgg/server/eventlistener/handler/OrderCouponUsedEventHandler.java
- src/main/java/com/nhnacademy/marketgg/server/eventlistener/handler/OrderPointCanceledEventHandler.java
- src/main/java/com/nhnacademy/marketgg/server/eventlistener/handler/OrderPointSavedEventHandler.java
- src/main/java/com/nhnacademy/marketgg/server/eventlistener/handler/OrderProductUpdatedEventHandler.java
- src/main/java/com/nhnacademy/marketgg/server/repository/pointhistory/PointHistoryRepositoryImpl.java
- src/main/java/com/nhnacademy/marketgg/server/repository/usedcoupon/UsedCouponRepositoryCustom.java
- src/main/java/com/nhnacademy/marketgg/server/repository/usedcoupon/UsedCouponRepositoryImpl.java
- src/main/java/com/nhnacademy/marketgg/server/service/order/DefaultOrderService.java
- src/main/java/com/nhnacademy/marketgg/server/service/order/OrderService.java
- src/main/java/com/nhnacademy/marketgg/server/service/payment/PaymentService.java
- src/main/java/com/nhnacademy/marketgg/server/service/payment/TossPaymentService.java
- src/main/java/com/nhnacademy/marketgg/server/service/point/DefaultPointService.java
- src/test/java/com/nhnacademy/marketgg/dummy/Dummy.java
- src/test/java/com/nhnacademy/marketgg/dummy/PaymentDummy.java
- src/test/java/com/nhnacademy/marketgg/server/controller/OrderControllerTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultOrderServiceTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultPointServiceTest.java
- src/test/java/com/nhnacademy/marketgg/server/service/payment/TossPaymentServiceTest.java
- close #297 
- 쿠폰, 포인트, 장바구니 세션 이용
- 포인트, 쿠폰 등 기타 수정사항 有
- 관련 도메인 담당 Reviewer 선정하였음
> 주문 Refactoring

- src/main/java/com/nhnacademy/marketgg/server/config/WebConfig.java
- src/main/java/com/nhnacademy/marketgg/server/filter/WhiteListFilter.java
- return 이 없어 검증 후 계속 진행되는 문제 해결
> Refactor: Filter 수정
